---
# arista_fabric_template

#########################################
# Comment the field that get data value from source path/file for proto type translation script
# Mentha Cheng will replace the below script
# Begin here
#########################################

tenants:
  - name: Tenant_A
    mac_vrf_vni_base: 10000
 
    vrfs:
      - name: bluevrf #-- From 5_segment/vrf.yaml "- VRF Name: bluevrf"
        vrf_vni: 10 #-- From 5_segment/vrf.yaml "VRF ID: 10"
        vtep_diagnostic:
          loopback: 100
          loopback_ip_range: 10.255.1.0/24

###### If 5_segment/network.yaml hostname -> "Layere2 Only: False", then add the below L3 config ######
        svis:
          - id: 2300 #-- From 5_segment/network.yaml "VLAN ID: 2300"
            name: bluenet1 #-- From 5_segment/network.yaml "- Network Name: bluenet1"
            vni_override: 32300 #-- From 5_segment/network.yaml "Network ID: 32300"
            tags: [bluenet1-tag]
            enabled: true
            ip_address_virtual: 192.168.11.1/24 #-- From 5_segment/network.yaml "IPv4 Gateway/NetMask: 192.168.11.1/24"

          - id: 2301 #-- From 5_segment/network.yaml "VLAN ID: 2301"
            name: bluenet2 #-- From 5_segment/network.yaml "- Network Name: bluenet2"
            vni_override: 32301 #-- From 5_segment/network.yaml "Network ID: 32301"
            tags: [bluenet2-tag]
            enabled: true
            ip_address_virtual: 192.168.12.1/24 #-- From 5_segment/network.yaml "IPv4 Gateway/NetMask: 192.168.12.1/24"

###### If 5_segment/network.yaml hostname -> "Layere2 Only: True", then add the below L3 config ######
    l2vlans:
      - id: 20 #-- From 5_segment/network.yaml "VLAN ID: 20"
        vni_override: 30020 #-- From 5_segment/network.yaml "Network ID: 30020"
        name: ExternalNetwork #-- From 5_segment/network.yaml "VLAN Name: ExternalNetwork"
        tags: [ExternalNetwork-tag] 


#########################################
# Comment the field that get data value from source path/file for proto type translation script
# End here
#########################################