---
# arista_fabric_template
network_ports:
  - switches:
      - s2-leaf1
    switch_ports:
      - Ethernet4
    enabled: true
    description: test eth4 access port
    mtu: 
    vlans: "2300"
    profile: int_access_host